# Generated by Django 2.2 on 2021-01-19 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hosts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='主机名')),
                ('ip_addr', models.CharField(max_length=32, verbose_name='ip地址')),
            ],
            options={
                'verbose_name': '主机表',
                'verbose_name_plural': '主机表',
                'db_table': 't_hippo_hosts',
            },
        ),
    ]
