# Generated by Django 2.2 on 2021-01-25 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hosts',
        ),
    ]
