# Generated by Django 2.2 on 2021-01-26 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('host', '0002_delete_hosts'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_show', models.BooleanField(default=False, verbose_name='是否展示')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否刪除')),
                ('orders', models.IntegerField(default=1, verbose_name='排序')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(auto_now_add=True, verbose_name='修改时间')),
                ('name', models.CharField(max_length=32, verbose_name='主机类型')),
            ],
            options={
                'db_table': 't_hippo_hostcategory',
            },
        ),
        migrations.CreateModel(
            name='Hosts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_show', models.BooleanField(default=False, verbose_name='是否展示')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否刪除')),
                ('orders', models.IntegerField(default=1, verbose_name='排序')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(auto_now_add=True, verbose_name='修改时间')),
                ('hostname', models.CharField(max_length=32, verbose_name='主机名')),
                ('ip_addr', models.CharField(max_length=32, verbose_name='ip地址')),
                ('port', models.IntegerField(verbose_name='ssh端口')),
                ('desc', models.CharField(max_length=255, verbose_name='描述信息')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hc', to='host.HostCategory', verbose_name='主机类别')),
            ],
            options={
                'verbose_name': '主机表',
                'verbose_name_plural': '主机表',
                'db_table': 't_hippo_hosts',
            },
        ),
    ]
