# Generated by Django 2.2 on 2021-01-26 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0003_hostcategory_hosts'),
    ]

    operations = [
        migrations.CreateModel(
            name='PkeyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_show', models.BooleanField(default=False, verbose_name='是否展示')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否刪除')),
                ('orders', models.IntegerField(default=1, verbose_name='排序')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(auto_now_add=True, verbose_name='修改时间')),
                ('key', models.CharField(max_length=50, unique=True)),
                ('value', models.TextField()),
                ('desc', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 't_hippo_host_secretkey',
            },
        ),
    ]
