# Generated by Django 2.2 on 2021-01-26 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0004_pkeymodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='hosts',
            name='username',
            field=models.CharField(default='test', max_length=50, verbose_name='登录用户名'),
            preserve_default=False,
        ),
    ]
