# Generated by Django 2.2 on 2021-01-26 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0005_hosts_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostcategory',
            name='is_show',
            field=models.BooleanField(default=True, verbose_name='是否展示'),
        ),
        migrations.AlterField(
            model_name='hosts',
            name='is_show',
            field=models.BooleanField(default=True, verbose_name='是否展示'),
        ),
        migrations.AlterField(
            model_name='pkeymodel',
            name='is_show',
            field=models.BooleanField(default=True, verbose_name='是否展示'),
        ),
    ]
